### ISSUE TITLE
The Apogee Throwback Pack (238050)

### ISSUE THREAD

**Issue by MicrosoftTakeover** [dreamer/boxtron#14]
## Compatibility Report
- Link to Steam store: https://store.steampowered.com/app/238050/
- Link to ProtonDB: https://www.protondb.com/app/238050

### System Information
- Linux distribution: Arch Linux
- Kernel: 5.1.15-zen1-1-zen
- Desktop: i3
- DOSBox: 0.74-3

### Report
- The game runs out of the box: No

### Configuration changes
None.

### Report
This pack of games has a launcher like the Sierra games do. It doesn't work with Proton or steam-dos.

https://steamdb.info/depot/238051/

Here's the contents of 'GamePaths.txt, the file that the launcher uses to detect games.
```
// This file stores the execution paths to the four games included in the throwback pack.
// Please backup this file before attempting to make alterations! Alterations is at your own risk.

// HOW TO USE:
// The four game names in front of the equals sign indicates the game.
// The path after it indicates the path to the games executable RELATIVE to the ThrowBackLauncher's location.
// If for example you had WinROTT and would like to use that instead of the Rise of the Triad included in the pack you would do the following:
// -Put the WinROTT folder in the same directory as the other game's folders.
// If we assume WinROTT's folder is named "WinROTT" and it's executable file is "WinROTT.exe", you would change the RiseOfTheTriad line in this file to be:
// RiseOfTheTriad=WinROTT\WinROTT.exe

// That's it. From then on, selecting Rise of the Triad in the launcher and clicking the "launch this game" button will now launch WinROTT.

// The original paths:
// RiseOfTheTriad=Rise of the Triad.bat
// RiseOfTheTriadExtreme=Extreme ROTT.bat
// BlakeStoneAliensOfGold=Aliens of gold.bat
// BlakeStonePlanetStrike=Planet Strike.bat

// The game executable paths

RiseOfTheTriad=Rise of the Triad.bat
RiseOfTheTriadExtreme=Extreme ROTT.bat
BlakeStoneAliensOfGold=Aliens of gold.bat
BlakeStonePlanetStrike=Planet Strike.bat
```

Here's the contents of 'Rise of the Triad.bat'
```
@echo off
cd dosbox
dosbox.exe -conf "ROTT.conf" -noconsole -c
exit
```

If you need any more information from game files let me know.

**Comment by dreamer** [comment]
Hmm, in theory something like `SDOS_RUN_EXE="Rise of the Triad.bat" %command%` could work here, but it won't in version 0.4.0, because I do not employ detection of batch files when injected with `SDOS_RUN_EXE` variable… I'll need to change it a bit.

**Comment by dreamer** [comment]
Ops, GitHub closed this automatically, which was not my intention, this needs to be tested first. I improved handling of .bat files, so more complex files like `Rise of the Triad.bat` qualify as "trivial" now.

@MicrosoftTakeover 
Can you test using launch options: `BOXTRON_RUN_EXE="Rise of the Triad.bat" %command%`?

**Comment by MicrosoftTakeover** [comment]
As we discussed on Discord, the launch options are working. Thanks.
