### ISSUE TITLE
Blood: One Unit Whole Blood (Steam 299030)

### ISSUE THREAD

**Issue by FurtadoPires** [dreamer/boxtron#27]
## Compatibility Report
- [Steam](https://store.steampowered.com/app/299030/Blood_One_Unit_Whole_Blood/)
- [ProtonDB](https://www.protondb.com/app/299030)

### System Information
- Linux distribution: Mint 19.2
- Kernel:  4.15.0-64
- Desktop: Cinnamon
- DOSBox: 0.74

### Report
- The game runs out of the box: No

### Report

-Tried to launch the game using boxtron, the game display a low memory warning than crash after press any key.

**Comment by dreamer** [comment]
Feel free to reopen this issue when some additional information will be available. As for now, I can't do a thing without co-operation from bug reporter.
