### ISSUE TITLE
Instructions to test dosbox-stagging are wrong

### ISSUE THREAD

**Issue by neuromancer** [dreamer/boxtron#28]
The latest release note says:

```
To accompany this Boxtron release, I prepared an experimental DOSBox build from the dosbox-staging repo. To test it, download the package, unpack it somewhere and configure Boxtron to use it by changing/adding following line in your ~/.config/boxtron.conf:

cmd = ~/<your-path>/dosbox-staging/dosbox
```

However, if you create your boxtron.conf file with only that line, boxtron will fail to parse it. You need to use:

```
[dosbox]
cmd = ~/<your-path>/dosbox-staging/dosbox
```

**Comment by dreamer** [comment]
Thanks for spotting this. I reworded the sentence to indicate that this line is in "dosbox" section.  Hopefully most users are not going to create this file by hand - it is being created automatically on first run.

In future versions I might drop the sections altogether - there's not enough options to be grouped and I don't intend to introduce more.

**Comment by neuromancer** [comment]
> Hopefully most users are not going to create this file by hand - it is being created automatically on first run.

That right, however, if you want to start using boxtron with the dosbox-stagging, that file will not be created and the user will (most likely) create this file from scratch following the instructions.

**Comment by dreamer** [comment]
The file is created by Boxtron, not dosbox-staging. The issue happens only when user never used Boxtron before and want to start using it with dosbox-staging right from the beginning (dosbox-staging is being tested, it didn't replace system dosbox as default dosbox implementation yet).
