### ISSUE TITLE
302364 - Tex Murphy: The Pandora Directive Linux

### ISSUE THREAD

**Issue by arrowgent** [dreamer/boxtron#38]
## Compatibility Report
- Link to Steam store: https://store.steampowered.com/app/302360/Tex_Murphy_The_Pandora_Directive/
- Link to GOG store:  
- Link to ProtonDB: 

### System Information
- Linux distribution: Ubuntu 18.04 LTS (LinuxMint 19.3)
- Kernel: 4.15.0-88-generic
- Desktop: Mate 1.24
- DOSBox: 0.74-5-2 SVN

### Report
- The game runs out of the box: Yes

### Report

Boxtron

**Comment by JoshuaFern** [comment]
Thanks for all your compatibility reports, but the issues section of github is for reporting bugs :)

You can edit the wiki here instead: https://github.com/dreamer/boxtron/wiki/Compatibility-reports

**Comment by arrowgent** [comment]
> Thanks for all your compatibility reports, but the issues section of github is for reporting bugs :)
> 
> You can edit the wiki here instead: https://github.com/dreamer/boxtron/wiki/Compatibility-reports

i have tried that.... gives me a 404 error.....
https://github.com/dreamer/boxtron/wiki/Compatibility-reports-%28Steam%29/_edit

**Comment by dreamer** [comment]
@arrowgent I think we renamed the page some time ago: https://github.com/dreamer/boxtron/wiki/Compatibility-reports

**Comment by arrowgent** [comment]
found the "edit" button.  thanks
