### ISSUE TITLE
added boxtron support in my steamtinkerlaunch wrapper script

### ISSUE THREAD

**Issue by frostworx** [dreamer/boxtron#40]
Hi,
just wanted to let you know that I added boxtron support in v1.0.2 of my linux wrapper script steamtinkerlaunch (or short stl)
https://github.com/frostworx/steamtinkerlaunch
Either enabled inside the gameconfig or simply add a game to the steam category DOSBox to automatically start it with boxtron.
Also planning to add  luxtorpeda and roberta support.
Sorry if it is inappropriate to open a issue for this!

**Comment by JoshuaFern** [comment]
Looks neat, thanks for sharing.
