### ISSUE TITLE
boxtron's displayed proton version according to steam config files.

### ISSUE THREAD

**Issue by arrowgent** [dreamer/boxtron#41]
i noticed boxtron is identified by steam as being Proton 4.2

if we look at the file

```
/home/$USER/.steam/steam/SteamApps/compatdata/2300/version
```
its identified as
```
4.2-2
```

but if we look at
```
/home/$USER/.steam/steam/logs/compat_log.txt
```
it is properly identified as
```
Mapping AppID 2300 to tool boxtron with priority 250
```

by comparison, proton-GE is recognized correctly
for example:
```
5.9-GE-5
```

is this just a limitation of steam or is boxtron compatibilitytools.d somehow marking this information?

is it possible to set this information to be unique for boxtron?

i dont fully understand how steam stores which proton version is selected, so i might just be looking at useless information as a whole.

**Comment by dreamer** [comment]
This is something new, I'll look into it - thank you for the report. Internal Boxtron name is `boxtron` or `boxtron_dev` (depending on the version installed).

Boxtron never tries to pretend to be Proton - perhaps `compatibilitytool.vdf` file format changed lately?

@arrowgent Do you use stable Steam or Beta?

**Comment by arrowgent** [comment]
i use steam beta.

i only recently noticed this because i was writing a script to display ALL proton selections for ALL steamplay games.

```
/home/$USER/.steam/steam/compatibilitytools.d/boxtron-installer/
```
does not have a compatibilitytool.vdf file

**Comment by arrowgent** [comment]
comparing proton-ge it does have compatibilitytool.vdf

boxtron only seems to have this
https://github.com/dreamer/boxtron/blob/master/compatibilitytool.template

let me try copying proton-ge's file, editing it, and seeing if it modifies the version

**Comment by arrowgent** [comment]
looking at how proton handles it,
in proton.py

this is where it creates this version 
```
class CompatData:
    def __init__(self, compatdata):
        self.base_dir = compatdata + "/"
        self.prefix_dir = self.path("pfx/")
        self.version_file = self.path("version")
        self.tracked_files_file = self.path("tracked_files")
        self.prefix_lock = FileLock(self.path("pfx.lock"), timeout=-1)
```
and then checks and updates the reported version
```
        os.remove(self.tracked_files_file)
        os.remove(self.version_file)

    def upgrade_pfx(self, old_ver):
        if old_ver == CURRENT_PREFIX_VERSION:
            return

        log("Upgrading prefix from " + str(old_ver) + " to " + CURRENT_PREFIX_VERSION + " (" + self.base_dir + ")")
```

since boxtron is not proton, it doesnt require this python code for compatibility compliance

**Comment by dreamer** [comment]
> comparing proton-ge it does have compatibilitytool.vdf
> 
> boxtron only seems to have this
> https://github.com/dreamer/boxtron/blob/master/compatibilitytool.template

As name suggests, this is only a template. `compatibilitytool.vdf` file is being generated when you do `make install` or `make dev-install`. It's also pre-generated in a tarball and installation packages.

**Comment by arrowgent** [comment]
hmm interesting, i dont think i did `make install`
probally just make then copied the files into the folder manually

> > comparing proton-ge it does have compatibilitytool.vdf
> > boxtron only seems to have this
> > https://github.com/dreamer/boxtron/blob/master/compatibilitytool.template
> 
> As name suggests, this is only a template. `compatibilitytool.vdf` file is being generated when you do `make install` or `make dev-install`. It's also pre-generated in a tarball and installation packages.

**Comment by arrowgent** [comment]
since this file is created by proton specifically and doesnt effect boxtron at all, ill close this to avoid any unrelated open issues

also since boxtron is avoiding wine/proton emulation the PFX situation also becomes irrelevant because it shouldnt modify the compatdata folders at all (because linux dosbox)
