### ISSUE TITLE
Doom 1 & Doom 2 - new bethesda port (steam)

### ISSUE THREAD

**Issue by arrowgent** [dreamer/boxtron#42]
https://slayersclub.bethesda.net/en/article/Cfuf9wL5enNxkx90hfJ21/doom-and-doom-ii-update-september-3

https://store.steampowered.com/app/2280
https://store.steampowered.com/app/2300

anyone tried boxtron with the new forced update?
i refuse to update....sorry

just making this note incase anyone wants to confirm compatibility issues

**Comment by dreamer** [comment]
Uh, just started the installation, but the game now weights 430 MB… does not bode well.

**Comment by dreamer** [comment]
OK, they just added new, "great", Unity-based implementation of Doom - that's what weigh those 400MB. But they preserved original DOS version (thankfully). 

When starting select "Launch DOS Version" or "Launch DOS version with classic controls" and Boxtron happily auto-detects the settings and everything works as it should :)

I haven't tested Doom II yet.
